### ISSUE TITLE
@lubgbrawl - Когда релиз ребёнок? Снесу к хуям вашу вдс(там после перезагрузки айпи и порт меняются) и вы будете делать новый client каждую минуту

### ISSUE THREAD

**Issue by crceck123** [TheAcelot/loshara#1]
![0_Screenshot_2022-02-13-10-25-55-23](https://user-images.githubusercontent.com/100026828/177038028-62898c59-1db4-4527-8bbf-bb3161623822.jpg)
ещё вот айпи вдсок лубг бравла
 144.130.171.230144.130.171.230 60.8.7.2660.8.7.26 123.252.204.130123.252.204.130 82.81.163.20282.81.163.202 123.56.92.41123.56.92.41

**Comment by TheAcelot** [comment]
👨🏿‍🦼

**Comment by crceck123** [comment]
🤸🏿‍♀️

**Comment by crceck123** [comment]
блять

**Comment by crceck123** [comment]
похуй

**Comment by TheAcelot** [comment]
👨🏿‍🦼
